language: java
sudo: false
jdk: oraclejdk8
install: mvn -T 4 ${CDH} ${SPARK} ${SCALA} -Ptravis -DskipTests=true -B -V install
script:  mvn -T 2 ${CDH} ${SPARK} ${SCALA} ${JACOCO} -Ptravis -q -B verify
env: JACOCO=-Pjacoco CDH=-Pcdh57
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
