language: java
sudo: false
jdk: oraclejdk8
install: mvn ${CDH} ${SPARK} ${SCALA} -Ptravis -DskipTests=true -Dmaven.javadoc.skip=true -B -V install
script:  mvn ${CDH} ${SPARK} ${SCALA} ${JACOCO} -Ptravis -Dmaven.javadoc.skip=true -q -B verify
matrix:
 include:
   # Covers code coverage, Spark 1.5
   - env: JACOCO=-Pjacoco
   # Covers Spark 1.6
   - env: SPARK=-Pspark-1.6
   # Covers CDH 5.6
   - env: CDH=-Pcdh56
cache:
  directories:
    - $HOME/.m2
git:
  depth: 10
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
