language: java
sudo: false
install: mvn -Pjava${JAVA_VERSION} ${CDH} -DskipTests=true -Dmaven.javadoc.skip=true -B -V install
script: mvn -Pjava${JAVA_VERSION} ${CDH} ${JACOCO} -Dmaven.javadoc.skip=true -q -B verify
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JAVA_VERSION=7 JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK, CDH5
   - jdk: oraclejdk8
     env: JAVA_VERSION=8 CDH=-Pcdh5
cache:
  directories:
    - $HOME/.m2
git:
  depth: 5
after_success: bash <(curl -s https://codecov.io/bash)
