language: java
before_install: sudo pip install codecov
script: mvn -Pjava${JAVA_VERSION} -Pjacoco clean test
jdk:
  - oraclejdk8
env:
  matrix:
    - JAVA_VERSION=1.7
    - JAVA_VERSION=1.8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 1
after_success: codecov
